tasks:
  - name: Dependencies & Database
    init: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      sqlite3 db.sqlite3 < data.sql
    