tasks:
  - name: Installing dependecies
    command: pip install -r requirements.txt

  - name: Creating migrations
    command: python manage.py makemigrations

  - name: Migrating
    command: python manage.py migrate